### ISSUE TITLE
Python client `SEGFAULT`s instead of calling `CustomWriteFunction`/`CUSTOM_WRITE`s in `parse_as_files`/`parse_as_files_custom`

### ISSUE THREAD

**Issue by james-clemer-actblue** [washingtonpost/FastFEC#29]
It seems like calls of `context->customWriteFunction` are going amiss. I'm seeing `SEGFAULT`s coming without any evidence that the custom open function or write callback are ever called.

I've tried to demonstrate that the custom function passed in is called via `print` statements followed by `stdout` flushes, and by`breakpoint`s, but have seen no evidence that the FFI is behaving as one would hope. The problem persists with calls to `parse_as_files`, as well.

To recreate, one can run:

```
import smart_open
from fastfec import *


if __name__ == "__main__":
    headers = {'headers': {'User-Agent': 'Mozilla/5.0'}}
    with smart_open.open(f'http://docquery.fec.gov/dcdev/posted/1606847.fec', 'rb', transport_params=headers) as f:
        with FastFEC() as fastfec:
            fastfec.parse_as_files(f, "some_output_directory", include_filing_id='1606847')
```

On at least revision `460d0c4`, built on MacOS and run on MacOS.

As I understand it, somewhere in [writer.c's call of the custom function being handed in from the python client](https://github.com/washingtonpost/FastFEC/blob/develop/src/writer.c#L256), there seems to be something going wrong.

The issue presented here is the smallest bit I could get to fail easily without getting rid of, for example, the use of `smart_open` (in the event that that's causing problems), but I'd ideally be able to use `fastfec.parse_as_files_custom` in a more general case, with other file-like objects. This is simply the smallest failing case I could demonstrate.

I'll keep looking at this as time and priority allow, but I figured a GH issue might be helpful in this instance.

**Comment by james-clemer-actblue** [comment]
Okay, so I have a theory, which is that when we call `context->customWriteFunction`, we haven't ensured that`bufferFile->buffer` is a null-terminated `char*`.
Which seems to be supported by the [docs for `c_char_p`](https://docs.python.org/3/library/ctypes.html#ctypes.c_char_p).
Trying to find proof now.

**Comment by freedmand** [comment]
Hey James, that makes sense, and TIL `c_char_p` is intended for null-terminated char*. That would probably explain it — thanks for digging! I see you're maintaining a separate branch. I'm not sure how this repo's settings work, but is it possible to open a PR against this repo?

**Comment by james-clemer-actblue** [comment]
You bet; I just need to get my time together a bit better. Aiming for one soon as I do so.
