### ISSUE TITLE
fastfec 0.1.6 regression test failed

### ISSUE THREAD

**Issue by chenrui333** [washingtonpost/FastFEC#43]
While [upgrading fastfec to 0.1.6](https://github.com/Homebrew/homebrew-core/pull/107476), I found that the test behavior got changed a bit.

The following test no longer works:
```
$ /opt/homebrew/Cellar/fastfec/0.1.6/bin/fastfec --no-stdin 13425
About to parse filing ID 13425
Trying filename: (null)
Couldn't open file: (null)
```

This is the old working test:
```
$ /opt/homebrew/Cellar/fastfec/0.0.4/bin/fastfec --no-stdin 13425
About to parse filing ID 13425
Trying URL: https://docquery.fec.gov/dcdev/posted/13425.fec
Done; parsing successful!
```

**Comment by freedmand** [comment]
Hi @chenrui333, just taking a look at all this now. Thank you for reporting! Per #33 this is an expected regression, and I believe your modification in https://github.com/Homebrew/homebrew-core/pull/107476/files addresses it. Let me know if anything further is needed on this one.
