### ISSUE TITLE
some normal/to be expected errors crash the c process; it would be better if they bubbled up to python

### ISSUE THREAD

**Issue by avitalb** [washingtonpost/FastFEC#48]
When running the fastfec from Python, some errors piped to stderr such as 
`fprintf(stderr, "Unknown type (%c) in %s\n", type, ctx->formType);` will `exit 1` and cause the program to crash. 
For errors in `fec.c`, it would be a better user experience if those errors bubbled up to `python` where they could be caught and give a more informative error message.

**Comment by james-clemer-actblue** [comment]
https://github.com/washingtonpost/FastFEC/pull/49 relates to this
